import { useState } from 'react';

function EditResumeModal({ match, onClose }) {
  const [selectedBullets, setSelectedBullets] = useState(
    match.tailoredBullets.map(() => true)
  );

  const toggleBullet = (index) => {
    const newSelected = [...selectedBullets];
    newSelected[index] = !newSelected[index];
    setSelectedBullets(newSelected);
  };

  const handleDownload = () => {
    // Create a simple text version for download
    const selectedText = match.tailoredBullets
      .filter((_, index) => selectedBullets[index])
      .map((bullet, index) => `${index + 1}. ${bullet}`)
      .join('\n\n');

    const content = `TAILORED RESUME BULLETS\n\n${selectedText}\n\n---\n\nGenerated by ResumeIQ - Smart Resume Analysis, Powered by AI`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'tailored-resume-bullets.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
      <div className="bg-white rounded-lg max-w-3xl w-full max-h-[90vh] overflow-y-auto">
        <div className="p-6 border-b border-gray-200 flex justify-between items-center">
          <h2 className="text-2xl font-bold">Edit Tailored Resume</h2>
          <button
            onClick={onClose}
            className="text-gray-500 hover:text-gray-700 text-2xl"
          >
            ×
          </button>
        </div>

        <div className="p-6">
          <p className="text-gray-600 mb-6">
            Select the bullets you want to include in your resume. Click to toggle.
          </p>

          <div className="space-y-4 mb-6">
            {match.tailoredBullets.map((bullet, index) => (
              <div
                key={index}
                onClick={() => toggleBullet(index)}
                className={`p-4 border-2 rounded-lg cursor-pointer transition-all ${
                  selectedBullets[index]
                    ? 'border-primary-600 bg-primary-50'
                    : 'border-gray-200 bg-gray-50 opacity-50'
                }`}
              >
                <div className="flex items-start gap-3">
                  <input
                    type="checkbox"
                    checked={selectedBullets[index]}
                    onChange={() => toggleBullet(index)}
                    className="mt-1"
                  />
                  <div className="flex-1">
                    {match.originalBullets[index] && (
                      <p className="text-sm text-gray-500 mb-2 italic">
                        Original: {match.originalBullets[index]}
                      </p>
                    )}
                    <p className="text-gray-900">{bullet}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>

          <div className="flex gap-4">
            <button onClick={onClose} className="btn btn-secondary flex-1">
              Cancel
            </button>
            <button
              onClick={handleDownload}
              disabled={!selectedBullets.some(Boolean)}
              className="btn btn-primary flex-1"
            >
              Download Selected ({selectedBullets.filter(Boolean).length})
            </button>
          </div>

          <p className="text-sm text-gray-500 mt-4 text-center">
            Note: This downloads a text file. For PDF generation, copy the bullets
            into your resume template.
          </p>
        </div>
      </div>
    </div>
  );
}

export default EditResumeModal;
