import { useState } from 'react';

function PDFDownloadButton({ match }) {
  const [loading, setLoading] = useState(false);

  const handleDownload = async () => {
    setLoading(true);
    
    try {
      // In a real implementation, this would call the backend PDF generation endpoint
      // For now, we'll create a simple text download
      const content = `
TAILORED RESUME
Generated by AI Resume Matcher

MATCH SCORE: ${match.score}%

AI-TAILORED BULLETS:
${match.tailoredBullets.map((bullet, i) => `${i + 1}. ${bullet}`).join('\n')}

MISSING SKILLS:
${match.missingSkills.join(', ')}

RECOMMENDATIONS:
${match.atsRecommendations.join('\n')}
      `.trim();

      const blob = new Blob([content], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `tailored-resume-${Date.now()}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Download failed:', error);
      alert('Failed to download resume');
    } finally {
      setLoading(false);
    }
  };

  return (
    <button
      onClick={handleDownload}
      disabled={loading}
      className="btn btn-primary"
    >
      {loading ? 'Generating...' : 'Download Resume'}
    </button>
  );
}

export default PDFDownloadButton;
